### ISSUE TITLE
Metal is using a deprecated Web API

### ISSUE THREAD

**Issue by fernandosouza** [metal/metal.js#162] opened 2016-09-28 02:33 UTC
Metal uses Event.initEvent() to initialize the value of an event created using document.createEvent() but Event.initEvent() is now deprecated.

https://developer.mozilla.org/en-US/docs/Web/API/Event/initEvent

We should drop it in the future. Right?

**Comment by mairatma** [comment] 2016-09-28 13:01
Interesting, I didn't know this was deprecated. The problem is that we need this to work on all browsers, and the alternative given to this api is one that apparently works only on IE >= 11 (at least that's what the compatibility table says on the page MDN links to for it: https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Creating_and_triggering_events). If that's the case then we need to keep using this until we can drop IE9 and IE10.

**Comment by mairatma** [comment] 2016-10-13 15:29
I'll close this since it seems like we need to keep using this api for all browsers to work. Besides, this function is only used by `dom.triggerEvent`, which in turn is only used by tests, so this should be fine for now :)

**Closed as completed by mairatma** 2016-10-13 15:29 UTC
